### ISSUE TITLE
DropdownMenu: Design component in Figma

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#1073]
### Design requirements
- Should have a visually appealing design that adheres to the overall application's theme.
- Should support different sizes and be resizable to accommodate various content lengths.

### Design tasks

- [x] Design is fully specified in Figma
  - [x] Design component with all relevant states
  - [x] Do a accessibility test of the sketches
  - [x] Functionality/animation is described and prototyped if relevant    
  - [x] If there are used any svgs in this component is it available for the developer? 
  - [x] Link to Figma design: https://www.figma.com/file/V4dzf3m1sapmU048OQnu7L/Arbeidsomr%C3%A5de%3A-Felles-komponenter?type=design&node-id=2%3A97320&mode=design&t=Iaaxfz21C2U7OXSv-1
  - [x] Pasted screenshot from Figma below :point_down:
  

![Image](https://github.com/digdir/designsystem/assets/13560642/b1e68196-d6a4-46bc-a88e-1fc229f18313)

**Comment by mrosvik** [comment]
Teste skalering

**Comment by Febakke** [comment]
## Review
**Overwriting:** Texts dissapear between sizes. To fix this we need to put all the group components into one component. So that you can switch between sizes. The negative side of this is that we will lose the clean right panel when we get in a size prop we dont want the user to touch. 

Another way might be to create one group component with three sizes and have one component that use that core group component. We might get a clean props panel and keep texts when the user change size on the **menu. 

**Handling of texts:** Should the text continue on one line or break? 

Will continue tomorrow!

**Comment by Thuneer** [comment]
Think I fixed it now, will you take a look @Febakke 😄 
I made it into 1 component, and changing both sizes and groups seems to keep the text values.
Text should break I think, that is how I have it setup now.

**Comment by Febakke** [comment]
Looks great!
