### ISSUE TITLE
Select: Problems with scroll

### ISSUE THREAD

**Issue by xmrsa** [digdir/designsystem#368]
### Description of the bug

Rullegardinen for å hoppe til sider lenger ut i skjemaet fungerer veldig dårlig i forhold til scrolling. Når man har behov for denne funksjonaliteten har man vanligvis mange sider i skjemaet. Når man starter opp utviklerverktøyet får man kun opp 3 sider i den synlige delen av rullegardinen. Jeg kan ikke skrolle nedover i lista med musa (med piltastene kommer man seg strengt tatt nedover, men det er lite oversiktlig). For å få opp en fullt navigerbar rullgardin må jeg dra i de 3 prikkene for å gjøre visningen av utviklerverktøyet større. Da blir det ikke så mye igjen av resten av skjermen (med mindre jeg har satt skjermen på høykant).
Kunne man f.eks. heller ha hatt pdf-knappen i en egen fane, og så fjerne eller legge teksten "Navigasjon" til venstre for rullegardinen? Da ville man fått plass til mer. Ellers må man ha en dropdown som er sånn at den ikke havner utenfor skjermen, men utvider seg oppover når det ikke er plass.

### Steps To Reproduce

1. Run an app with more than 5 pages
2. Click the little square in the bottom right corner to start the Developer Tool
3. Try to pick a page late in the app by using the mouse (good luck with that, without expanding the area of the tool)

### Additional Information

![image](https://user-images.githubusercontent.com/42466346/237050327-cf0101d3-05c2-462f-9ad1-e6cd1ddc8e20.png)

**Comment by mimarz** [comment]
Hello! 👋 

Thank you so much for bringing this to our attention! There was a lot of description to unravel here but if I understood it correctly the problem was the `Select` dropdown opening up outside of the screen?

**Comment by rvessb** [comment]
Droppliste som åpnes "under" andre komponenter skaper problemer flere steder.  Her i gruppe konfigurert som onlyTable:
![image](https://github.com/digdir/designsystem/assets/43333852/36edf864-a95f-4f3b-a3cc-e214a91c743e)

**Comment by olemartinorg** [comment]
@mimarz Yup.
1. The `Select` component opens under other visual elements, it should not produce a scrollbar like it does in the above screenshot (see also the comment from @RonnyB71 [on slack](https://altinndevops.slack.com/archives/C03L53RFPRU/p1683638402557639))
2. The option list should be scrollable using a mouse, not just the keyboard
3. I believe the option list should expand upwards if there is not enough space below the component in the current viewport

**Comment by mimarz** [comment]
> @mimarz Yup.
> 
> 1. The `Select` component opens under other visual elements, it should not produce a scrollbar like it does in the above screenshot (see also the comment from @RonnyB71 [on slack](https://altinndevops.slack.com/archives/C03L53RFPRU/p1683638402557639))
> 2. The option list should be scrollable using a mouse, not just the keyboard
> 3. I believe the option list should expand upwards if there is not enough space below the component in the current viewport

Ah yeah, these are known issues. 🙈 

Its due to the dropdown container being inline in the DOM and using css/unmount rendering techniques. This works poorly due [The stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). This is why the content is pushed in the container making the scroll bars appear as well as it being "out of view" because the container is to small.

The same goes for where the dropdown pops up. It should always go where there is room :) 

There are ways to fix this, most common is to use a positioning library like [floating-ui](https://floating-ui.com/) (formerly popperjs). I have tried making positioning utilities in the past and I would not recommend anyone that pain and agony 😅 

Work has been started to use floating-ui on components in the react design system, but we are a bit in a limbo with Select/Combobox/Autocompletes as there are other bugs, features and components missing (as a whole) that we want to address. We're not sure if we are going to continue down the current path, rebuild or reuse something existing. 

I can't give you a clear answer when or how this will be fixed, but I'll bring it up at our next planning and get back to you :)

**Comment by mimarz** [comment]
We brought this up at the daily today and deemed this rather important to fix now whatever the future might bring, so we've prioritised it todo.

Here are some notes for the fixer :) 

- Get familiar with the floating-ui docs: https://floating-ui.com/docs/getting-started
- I have previously fixed it like this using floating-ui: https://github.com/equinor/design-system/blob/142d534e965ac95a0f4f10370207a17943b525bc/packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx#L550
