### ISSUE TITLE
Select: Specify z-index for floating ui

### ISSUE THREAD

**Issue by bjosttveit** [digdir/designsystem#497]
### Description of the bug

The z-index is currently hardcoded to 2, so if you put a Select inside of something with a higher z-index, the options will not be visible as they will be underneath and not clickable.

We need a way to set the z-index. This could be achieved either using a specific prop, or by adding an `optionsListClassName` or something to be able to override css-variables / styling for the options list.

### Steps To Reproduce

1. Place a Select inside of a wrapping element with z-index > 2
2. Click the select and no options will be visible

**Comment by mimarz** [comment]
Thanks for reporting this! 

This is actually a bigger issue that we haven't had a chance to look at yet. I've made a separate issue for this here #500 


This can easily be fixed by setting the `z-index={1500}` on the `Optionlist` here: https://github.com/digdir/designsystem/blob/69d74b268c7df78bcd33e5087ad3697f203f5cbe/packages/react/src/components/Select/OptionList/OptionList.tsx#LL59C36-L59C36
