### ISSUE TITLE
Button should use typography-component (react)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#553]

**Comment by framitdavid** [comment]
It is not advisable to directly use the Typography component within the Button component. The native button provides an API that follows the syntax <button>Hello</button>. This allows users to choose any content they prefer for the button, such as icons, text, images, and more. To maintain consistency with the native button API, it is recommended to follow the same approach.

If your intention is to ensure that the buttons use the same font size as the Typography component, I understand the reasoning. However, please note that the button is still utilizing the old tokens. Have you considered the impact of updating the tokens to the new ones? It would be important to assess how the buttons would appear once the token update is implemented.

When constructing a Pagination component or any other component that requires the usage of the Button component, you could explore an approach like this: <Button><Paragraph as="span">1</Paragraph></Button>. This way, you can include the necessary elements within the Button component instead of hard-code inside the button component.

**Comment by framitdavid** [comment]
Never mind the prev comment, we can of course use the "as=span" to render a un-semantic element with the correct styling. :)
