### ISSUE TITLE
Button: New variants

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#821]
Variant prop should include: 
- `Filled`, `outline`, `quiet` should be replaced by `primary`, `secondary` and `tertiary`. 

Color prop should include: 
- `Primary` and `secondary` should be replaced by `default` and `neutral` (in addition to `success` and `danger` that already exist)

**Comment by mimarz** [comment]
Should we also have a look at `Accordion` & `Tag` so that its abit more conformed across components? @mrosvik  Since we are now removing `primary` & `secondary` as colors from `Button`

**Accordion:**
`color?: 'primary' | 'secondary' | 'tertiary' | 'neutral' | 'subtle';`

**Tag:**
` color?: 'primary' | 'secondary' | 'tertiary' | 'neutral' | 'success' | 'warning' | 'danger' | 'info' `

**Comment by mimarz** [comment]
Decision on color namings in #828
